import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/landing/Banner'
import Header from '../components/navigation/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      <main className="">
        <Banner />
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
